name: ta-osso-backend

services:
  api:
    container_name: taosso-api
    image: taosso.api
    build:
      context: .
      dockerfile: TaOsso.Api/Dockerfile
    ports:
      - 3000:8080
    env_file:
      - .env.development
    depends_on:
      - postgres

  postgres:
    container_name: taosso-postgres
    image: postgres:16.4-alpine3.20
    ports:
      - 5432:5432
    env_file:
      - .env.development
    volumes:
      - taosso-postgres:/var/lib/postgresql/data

volumes:
  taosso-postgres:
    