[build]
builder = "DOCKERFILE"
dockerfilePath = "./TaOsso.Api/Dockerfile"

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "dotnet TaOsso.Api.dll"
sleepApplication = true
restartPolicyType = "NEVER"