name: Deploy to Railway

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 18
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          
      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        working-directory: backend
        run: railway up -s ta-osso-api
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
